### ISSUE TITLE
你好懒啊

### ISSUE THREAD

**Issue by Detector006** [LovelyZeeiam/LovelyZeeiam.github.io#1]
我觉得宁有必要学习一下WEB三大语言：HTML、CSS、JavaScript，这对你没有坏处。总是依赖Gridea不是一个明智的选择，虽然这会占用你的部分时间。我国有句古话：“磨刀不误砍柴工”，多写一点总是没有坏处的。而且你们做这么大的项目，这点东西免不了要做的，这些做好了，可以给你们的用户带来很好的体验，有百利而无一害。

**Comment by javaherobrine** [comment]
我表示这只是个个人博客而不是项目官网，官网在我这里。
个人博客用Gridea就可以了，但是HTML、CSS、JS的确要学，对web开发很有用

**Comment by LovelyZeeiam** [comment]
个人博客其实也可以当成官网 比如说更新日志之类的 还有下载路径 设个置顶------------------ 原始邮件 ------------------
发件人: "Java_Herobrine"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 上午9:49
收件人: "LovelyZeeiam/LovelyZeeiam.github.io"<LovelyZeeiam.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [LovelyZeeiam/LovelyZeeiam.github.io] 你好懒啊 (#1)




 
我表示这只是个个人博客而不是项目官网，官网在我这里。
 个人博客用Gridea就可以了，但是HTML、CSS、JS的确要学，对web开发很有用
 
&mdash;
