### ISSUE TITLE
宁的主页有点问题

### ISSUE THREAD

**Issue by javaherobrine** [LovelyZeeiam/LovelyZeeiam.github.io#2]
https://lovelyzeeiam.github.io/tags/
这个页面所有的元素的大部分被一张图片，通过F12调试界面发现，是一堆article元素被一个img元素挡住
这很影响用户体验

**Comment by LovelyZeeiam** [comment]
？我这里是正常的------------------ 原始邮件 ------------------
发件人: "Java_Herobrine"<notifications@github.com>
发送时间: 2020年4月9日(星期四) 上午10:03
收件人: "LovelyZeeiam/LovelyZeeiam.github.io"<LovelyZeeiam.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [LovelyZeeiam/LovelyZeeiam.github.io] 宁的主页有点问题 (#2)




 
网易云的那个按钮和GitHub的那个按钮，我鼠标拖上去时，显示的是Twitter，属性title的值有错
 然后我点了一下&#x5B81;那个头像，跳转的页面404了
 这些问题或多或少会影响用户的体验，建议修复一下
 
&mdash;

**Comment by javaherobrine** [comment]
我说的不是图标而是鼠标拖到图标上显示的内容，是Twitter
然后那个404建议修复一下：
点宁那个头像会跳转到https://lovelyzeeiam.github.io/%3E
这就是问题所在，地址不存在

**Comment by javaherobrine** [comment]
又出现了一堆bug

**Comment by javaherobrine** [comment]
现在又多了一个bug，影响体验的bug

**Comment by javaherobrine** [comment]
真的非常影响体验，一定要修复的一个bug
