### ISSUE TITLE
很好，已经不是问题了

### ISSUE THREAD

**Issue by javaherobrine** [LovelyZeeiam/LovelyZeeiam.github.io#3]
自己看看主页吧，存在的意义何在，那篇文章直接404了，F12打开控制台，js函数找不到，css也直接404
这已经是严重错误了

**Comment by LovelyZeeiam** [comment]
我上都上不去，怎么修。。。（︶︿︶）
反正本地是好的。



---原始邮件---
发件人: "Java_Herobrine"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 晚上6:29
收件人: "LovelyZeeiam/LovelyZeeiam.github.io"<LovelyZeeiam.github.io@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [LovelyZeeiam/LovelyZeeiam.github.io] 很好，已经不是问题了 (#3)




 
自己看看主页吧，存在的意义何在，那篇文章直接404了，F12打开控制台，js函数找不到，css也直接404
 这已经是严重错误了
